### ISSUE TITLE
Actions Per Minute counter continues to fall after game is complete

### ISSUE THREAD

**Issue by jimcullenaus** [alexwidua/aegis#4]
## To reproduce

1. Play a game to completion
2. View the "your result" screen, showing some value for APM (e.g. 60)
3. Wait a few seconds
4. Observe that the APM value has decreased

## Expected behaviour

APM value should remain constant while viewing the "your result" screen.

## Suspected cause & solution

I suspect game loop may be continually refreshing the `handleGameEnd` state and thus recalculating the `finishTime`, and from it, the `apm` value.

The easiest quick fix would probably be to set the `finishTime`  each time `handleSecondKeyCorrect` is called, where the `promptFinishTime` is already being updated. A more elegant solution might be to stop the state being continually refreshed, and only update state when a key is pressed.

But I haven't yet actually run this to test it, so my suspected cause & solution could be ***way*** off.

**Comment by alexwidua** [comment]
Hej @jimcullenaus,
thank you for this detailed issue.

You were right with your suspicion — the `handleGameEnd` was fired repeatedly because it was wrapped inside a `setInterval()` func. Using a `setTimeout()` func instead solved the issue. Thank you for bringing up this issue and I hope you had a great start into the year! Cheers 🥂

**Comment by jimcullenaus** [comment]
Cool, thanks for the info! Happy new year mate. Hope you have a good one.
